spring:
  application:
    name: myselectshop
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      sparta: debug
jwt:
  issuer: sparta.myselectshop
  secret-key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  access-expiration: 36000000
  refresh-expiration: 864000000

openapi:
  naver:
    client-id: 5rsgO1VtV_3hWx9JPXmb
    client-secret: pRr8gGqnjd


admin:
  token: AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC
